FROM debian:stretch

LABEL VENDOR="Freddy Heredia"
LABEL Description="Base Debian Lista para Trabajar"


COPY resources/sources.list /etc/apt/

ENV USUARIO ale
ENV CLAVE 123


RUN apt -y update \
    && apt -y upgrade \
    && useradd -m $USUARIO -p $CLAVE \
    && apt -y install openssh-server

CMD [""]

EXPOSE 22

